---
title: "COVID-19 Research Project"

author: "Lauren Thomas"

date: "`r format(Sys.time(), '%B %d, %Y')`"

output:

  rmarkdown::html_document:

    theme: cerulean

    highlight: monochrome
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)

library(tidyverse)
library(lubridate)
library(HelpersMG)
library(kableExtra)
library(tinytex)
```

```{r download_Data, echo = FALSE}
if(!file.exists("./raw_data/owid-covid-data.csv")) {
  wget(url = "https://covid.ourworldindata.org/data/owid-covid-data.csv", destfile = "./raw_data/owid-covid-data.csv")
}
 
if(!file.exists("./raw_data/OxCGRT_latest.csv")) {
  wget(url = "https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv", destfile = "./raw_data/OxCGRT_latest.csv")
}

```


```{r tidying, echo = FALSE}
read_csv("./raw_data/OxCGRT_latest.csv") %>%
  mutate(Date = ymd(Date)) %>%
  inner_join(read_csv("./raw_data/owid-covid-data.csv"), by = c("CountryCode" = "iso_code", "Date" = "date")) %>%
  write_csv("./output/covid_data.csv")

```

## Introduction

## Hypothesis

## Data 

### Analyses 
<br/>


```{r First_Case}
first_case <- read_csv("./raw_data/owid-covid-data.csv") %>%
	select("Total_Cases" = "total_cases", "Date" = "date", "Country" = "location") %>%
	filter(Total_Cases == 1, Date <= "2020-01-19") %>%
	arrange(Date) 
			
knitr::kable(first_case, caption = "First COVID-19 Case") %>%
	kable_styling(position = "float_left")

```
<br/>
<br/>

```{r Workplace_Thailand}

Workplace_Thailand <- read_csv("./output/covid_data.csv") %>%
	select("Ordinal Scale" = "C2_Workplace closing", "date" = "Date", "Country" = "CountryName") %>%
	filter(Country == "Thailand", date <= "2020-03-22", date >= "2020-03-15") %>%
	arrange(date) 
	

knitr::kable(Workplace_Thailand, caption = "First Workplace Restriction") %>%
	kable_styling()
	


```

<br/>
<br/>


```{r Workplace_Japan}
Workplace_Japan <- read_csv("./output/covid_data.csv") %>%
	select("Ordinal Scale" = "C2_Workplace closing", "date" = "Date", "Country" = "CountryName") %>%
	filter(Country == "Japan", date >= "2020-02-22", date <= "2020-02-29") %>%
	arrange(date)

knitr::kable(Workplace_Japan, caption = "First Workplace Restriction") %>%
	kable_styling()


```
<br/>
<br/>

```{r Cases_Before_Workforce}

Cases_Before_T <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Thailand", date <= "2020-03-17") %>%
	arrange(date)

Cases_Before_J <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Japan", date <= "2020-02-25") %>%
	arrange(date)

ggplot(data = Cases_Before_J, aes(x = date, y = Cases, color = Country)) + geom_line() + geom_line(data = Cases_Before_T, Colour = 'red') + labs(x = "Date", y = "Confirmed Cases") + theme_linedraw() + ggtitle("Confirmed COVID-19 Cases Before Workplace Restriction")






```
<br/>
<br/>

```{r Cases_After_Workforce}

Cases_After_T <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Thailand", date >= "2020-03-17") %>%
	arrange(date)

Cases_After_J <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Japan", date >= "2020-02-25") %>%
	arrange(date)

ggplot(data = Cases_After_J, aes(x = date, y = Cases, color = Country)) + geom_line() + geom_line(data = Cases_After_T, Colour = 'red') + labs(x = "Date", y = "Confirmed Cases") + theme_linedraw() + ggtitle("Confirmed COVID-19 Cases After Workplace Restriction")


```
<br/>
<br/>
<br/>

```{r Home_Thailand}

Home_Thailand <- read_csv("./output/covid_data.csv") %>%
	select("Ordinal Scale" = "C6_Stay at home requirements", "date" = "Date", "Country" = "CountryName") %>%
	filter(Country == "Thailand", date <= "2020-03-23", date >= "2020-03-15") %>%
	arrange(date)

knitr::kable(Home_Thailand, caption = "First Stay at Home Restriction") %>%
	kable_styling()


```
<br/>
<br/>

```{r Home_Japan}

Home_Japan <- read_csv("./output/covid_data.csv") %>%
	select("Ordinal Scale" = "C6_Stay at home requirements", "date" = "Date", "Country" = "CountryName") %>%
	filter(Country == "Japan", date <= "2020-04-09", date >= "2020-04-02") %>%
	arrange(date)


knitr::kable(Home_Japan, caption = "First Stay at Home Restriction") %>%
	kable_styling()


```
<br/>
<br/>

```{r Cases_Before_Home}

Cases_Be4_Home_T <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Thailand", date <= "2020-03-21") %>%
	arrange(date)


Cases_Be4_Home_J <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Japan", date <= "2020-04-07") %>%
	arrange(date) 



ggplot(data = Cases_Be4_Home_J, aes(x = date, y = Cases, color = Country)) + geom_line() + geom_line(data = Cases_Be4_Home_T, Colour = 'purple') + labs(x = "Date", y = "Confirmed Cases") + theme_linedraw() + ggtitle("Confirmed COVID-19 Cases Before Stay At Home Restriction")



```

```{r Cases_After_Home}

Cases_Af_Home_T <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Thailand", date >= "2020-03-21") %>%
	arrange(date)

Cases_Af_Home_J <- read_csv("./output/covid_data.csv") %>%
	select("date" = "Date", "Country" = "CountryName", "Cases" = "ConfirmedCases") %>%
	filter(Country == "Japan", date >= "2020-04-07") %>%
	arrange(date)



ggplot(data = Cases_Af_Home_J, aes(x = date, y = Cases, color = Country)) + geom_line() + geom_line(data = Cases_Af_Home_T, Colour = 'red') + labs(x = "Date", y = "Confirmed Cases") + theme_linedraw() + ggtitle("Confirmed COVID-19 Cases After Stay At Home Restriction")


```



## Conclusions

### Viewing this project
The completed project files can be accessed online at file:///Users/laurenthomas/COVID-19/README.html. The repo for this reproducible project is also publicly available at https://github.com/thomal29/COVID-19
